baseURL = 'https://jeffvansteijn.nl/'
languageCode = 'en-us'
title = 'Jeff'
theme = 'yaz'

[menu]

      [[menu.main]]
    identifier = "bikes"
    name = "Bikes"
    url = "/bikes/"
    weight = "-100"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -200
    
    
    [footer]
  [[menu.footer]]
    identifier = "colophon"
    name = "colophon"
    url = "/colophon/"
    weight = "10"
    
    
    [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true